### ISSUE TITLE
[Docs] forEach

### ISSUE THREAD

**Issue by hnordt** [rethinkdb/horizon#434]
In http://horizon.io/api/collection/#fetch the docs say:

> The Observable returned by fetch or watch may be iterated through with subscribe or forEach, or converted to an array with toArray.

``` js
const hz = Horizon();

hz("messages").fetch().subscribe(
    result => console.log('Result:', result),
    err => console.error(err),
    () => console.log('Results fetched')
);
```

How can I iterate a `fetch` query with `forEach`? 

``` js
const hz = Horizon();

// Of course this doesn't work
hz("messages").fetch().forEach(
    result => console.log('Result:', result),
    err => console.error(err),
    () => console.log('Results fetched')
);
```

**Comment by deontologician** [comment]
Hi @hnordt ,

While you can technically use forEach to iterate over results from a `.fetch()` it's usually not too useful, since what you'll be iterating is a single element that contains an array (or in the case of a `.find` query, a single object).

I would suggest doing something like:

``` js
hz('messages').fetch().subscribe({
 next(results) {
   for (const result of results) {
    ...
   }
 },
 error(err) { ... },
 complete() { ... }
})
```

[forEach is documented here](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-forEach), basically it returns a promise, which you can chain to or call `.catch` on to handle errors, so `forEach` itself only accepts one argument. forEach is a lot more useful on `.watch()` queries though, since you'll get more than one result

**Comment by deontologician** [comment]
I've opened an issue in our docs repo: rethinkdb/horizon-docs#56 to not suggest using forEach for fetch
