### ISSUE TITLE
connect/onReady is necessary?

### ISSUE THREAD

**Issue by hnordt** [rethinkdb/horizon#447]
Do I need to call `connect()` and use collection API inside a `onReady` handler?

The docs on http://horizon.io/api/horizon/ says that `connect()` is optional, so what's the difference between the two options?

``` js
// Option 1
const hz = Horizon();
horizon.onReady(() => {
  const messages = hz('messages');
  messages.store({ msg: 'Hello World!' });
});
hz.connect();

// Option 2
const hz = Horizon();
const messages = hz('messages');
messages.store({ msg: 'Hello World!' });
```

**Comment by danielmewes** [comment]
@hnordt There is no difference as far as I know, both work.

`connect()` will be automatically called once you perform any operation on a collection.

The default example generated by `hz init` uses these functions because it doesn't run any operations on a collection, so `connect()` would never get called otherwise.

**Comment by hnordt** [comment]
Thank you @danielmewes
