### ISSUE TITLE
Documentation for adding custom backend functionality

### ISSUE THREAD

**Issue by sunjay** [rethinkdb/horizon#466]
The [docs](http://horizon.io/faq/) specify that Horizon can be extended to add custom backend functionality:

> Horizon exposes a powerful API that allows writing sophisticated realtime applications. However, we carefully designed Horizon to provide an upgrade path in case your application outgrows the Horizon API. If you need to add backend functionality, instead of using the standalone Horizon server you can require Horizon in Node.js as a library, and mix and match Horizon services along with the rest of the Node.js ecosystem. Since Horizon is built on top of RethinkDB, your app will have full access to the underlying database, and you can write arbitrarily complex code without being limited by Horizon’s base APIs and tools.

However I haven't been able to find any documentation about how to do any of that. Can something about this be added? 

My use case is some rules that need to be enforced (and hidden). I can't manage with simple validation functions. I want to add a custom endpoint on the backend (or something of that nature) to run my code. How would this look with horizon? Would this be a custom endpoint or would I be adding a method to the horizon object? The docs would hopefully answer these questions.

**Comment by danielmewes** [comment]
Thanks for the feedback @sunjay.

@Tryneus can give you some pointers about where to put custom endpoints.
This comment by him might also be useful: https://github.com/rethinkdb/horizon/issues/337#issuecomment-219317195

Meanwhile, I opened https://github.com/rethinkdb/horizon-docs/issues/62 about adding documentation for this.

(closing the issue since the remaining work is going to happen in horizon-docs)
