### ISSUE TITLE
When not using `--serve-static`, a handler needs to be setup to correctly 404 requests

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#511]
Currently if you don't have `--serve-static` set, the browser will just hang until it times out when you go to any path on the domain (except for `/horizon/*` of course) `http[s]://localhost:8181`  It should immediately 404.

**Comment by deontologician** [comment]
So it looks like the reason this doesn't happen is because the fileServer assumes any paths it doesn't handle will be handled by the horizon server (we have two static file servers at this point, one the server manages, and one the cli manages). In reality of course, there are paths that neither the cli nor the server handle, and these hang forever.

I think the reasonable solution would be to get out of the business of running our own static file server, and pick a library to use for this. Then use that library in the horizon server, removing serving from the cli altogether.

@Tryneus thoughts?

**Comment by dalanmiller** [comment]
If we pick express, it wouldn't be ridiculous to just use passportjs after
that, no?

cc @marshall007

**Comment by deontologician** [comment]
Well express is kinda big for this, since it's meant for dynamic serving. We just need to serve files from a directory, give 404s on missing, give 500 on errors, pick the right mime-type etc. All stuff we've got coded ourselves at the moment (and not particularly cleanly). Plus, this wouldn't be used if the user is integrating Horizon into an existing app, only in the config/backendless mode

**Comment by marshall007** [comment]
@deontologician I've been talking to @dalanmiller recently and we've been trying to figure out at what point it makes sense to just adopt an existing server framework. With things like routing, static file serving, and authentication I've been feeling like we're right on the tipping point.

I don't think it matters how "big" it is. The important part is interoperability which is why I think `express` is probably the clear winner. Being able to attach arbitrary PassportJS strategies to your Horizon server is clearly a huge win over our existing solution. The same is true for this issue and things like CORS from #239. I think it would benefit everyone if we could push people towards existing middleware solutions rather than rolling our own.

Also note that just because we pick a framework, that doesn't mean we're giving up on attaching Horizon to your framework of choice. It's really straightforward to attach an `express` app to an existing `http.Server` instance.

**[edit]**: pinging @Tryneus too.

**Comment by deontologician** [comment]
I am mostly on board, I realized afterward my previous comment doesn't fully make sense. What the cli tool uses to serve routes doesn't restrict what someone does when using the horizon server as an import. If we design it right so it can be plugged into hapi and koa on the backend, and the horizon server module itself doesn't require you to buy into a particular middleware stack, then it should be good.

We should open a new issue for this though, since this is closed. @marshall007 would you mind writing up your proposal in a new ticket?

**Comment by marshall007** [comment]
@deontologician I think it's mostly covered by #24, so I just linked and copied over this discussion.
