### ISSUE TITLE
Add keepalives to protocol

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#527]
This is to avoid firewalls closing websocket connections, now that we've reverted back from engine.io as the transport

I propose we add a new message type 'keepalive' that's sent at a configurable interval from the ~~server~~ client and contains nothing else. `{ "type": "keepalive" }`. The default interval should probably be ~~30 minutes or something~~ 5 minutes

**Comment by danielmewes** [comment]
The client also needs to send keepalive messages, not just the server I think.
I also suggest that we make the interval significantly lower than 30 minutes. Maybe 5 minutes, or even less?

Apart from keeping routers from closing the connection, another important reason for sending keepalive messages is to detect when the connection has died. "Nothing" is worse than a realtime app that has silently stopped updating because the connection is dead. Sending something over the connection will make sure that the operating system notices if the TCP connection is no longer alive. Otherwise it could sit in a dead state over a long period and nobody would know.

**Comment by deontologician** [comment]
I meant client, but typed server for some reason. So is everyone ok with 5 minutes then?

**Comment by danielmewes** [comment]
Actually would it be hard to make the interval configurable? I think 5 minutes is a good default, but some people might prefer more frequent checks at the cost of slightly more server load.

**Comment by deontologician** [comment]
Yeah, I was planning on making it an option in the client

**Comment by babakness** [comment]
https://www.built.io/blog/2014/11/websockets-on-aws-elb/

In the comments from link:

> This issues seems to be happening because of the Idle timeout for requests in Amazon’s ELB, which is by default, 60 seconds.
> 
> You can find ‘Connection Settings’ attribute under ‘Description’ tab for ELB in AWS console. It can be modified as needed.
> 
> You have also mentioned heartbeat mechanism is in place, in such case, you’d need to ensure heartbeat frequency is less than 60 seconds to avoid losing the WebSocket connection.

Seems like a solid case for when you'd want heartbeats lower than 60 seconds.

**Comment by danielmewes** [comment]
That's interesting @babakness .

This makes me think that we should consider use a lower default so users don't have to deal with this when running on AWS.

I don't have a great understanding of how much load the heartbeats are actually going to cause. Maybe we should just benchmark their overhead once this is implemented. If the overhead is very low, we might want to go for something like 50 seconds by default.

**Comment by deontologician** [comment]
Implemented in #619
