### ISSUE TITLE
Reconnecting from client doesn't cause another ready event to be sent

### ISSUE THREAD

**Issue by nphyatt** [rethinkdb/horizon#595]
I'm writing something to handle reconnecting to the horizon server in case of disconnect. I listen for dissconnect using  

``` js
hz.onDisconnected(...);
```

and then retry connecting a specified number of times using

``` js
hz.connect();
```

however I never recieve another ready event after successful reconnect.
I continue to see error and disconnect events but I only ever see the one ready event.

**Comment by danielmewes** [comment]
I believe `connect` is lazy in the sense that if a connection already exists, it will not do anything.

If the connection is lost, I too would expect `hz.connect()` to re-establish the connection though. Is that what you're testing?

@deontologician What's the currently implemented behavior for this? Could this be a bug?

**Comment by nphyatt** [comment]
@danielmewes Basically I'm testing reconnect on loss of connection...particularly on mobile where wifi can be spotty. The horizon client doesn't seem to have a retry policy for reconnecting so I've written a wrapper on my end for now which listens for a `disconnected` event and then retries connecting a set number of times with some backoff using `hz.connect()`. I'm able to bring down the connection, and then reconnect but there are a couple issues. 
1. If I reconnect using `hz.connect()` anything I'm subscribed to will be lost.
2. If I want to wrap my subscribes in an `hz.onReady` or a custom `hz.onReconnect` in order to resubscribe any existing connections I don't get a `ready` event after successful reconnect and therefore I can't tell if I successfully reconnected.

**Comment by danielmewes** [comment]
Ok that makes sense.

Point 1 is expected currently. We're planning to solve this better in the future though and handle reconnects transparently without losing subscriptions (https://github.com/rethinkdb/horizon/issues/9)

The fact that a successful reconnect doesn't trigger the `onReady` callback sounds like a client bug to me (unless I misunderstand the expected semantics). We'll look into it.

**Comment by deontologician** [comment]
Ok! After reminding myself how the websocketsubject works, I realize this needs more of a fix than just #619. We need to actually create a new socket and connect it. Right now this is just subscribing to a dead observable.

That being said, `horizon.connect()` is being a bit misleading here. It wasn't intended to allow reconnection, just to force the socket to connect without having to actually emit a query (the default is that it lazily connects when you run your first query).

We could either lump this issue in with #9 or we could use this issue as an excuse to throw an exception if you try to `.connect()` once the underlying websocket is closed. I'm inclined towards the latter since there isn't a reasonable way to make this work until #9 is fully completed. Reconnecting has a lot of side-effects like all of your queries dying etc, so it isn't enough to just try creating a new socket.

**Comment by deontologician** [comment]
OK, for now I think I'm going to throw an exception if `.connect` is called after the socket closes
