### ISSUE TITLE
Switch to config.js

### ISSUE THREAD

**Issue by bopjesvla** [rethinkdb/horizon#629]
This would allow for modularisation of the configuration file and isomorphic, non-string validator functions.

**Comment by deontologician** [comment]
Hi @bopjesvla,

We discussed this previously in #84 and settled on toml because it's trivially parseable by languages other than javascript. This applies mostly to the table and index specifications, and is less important for the validators and template permissions (which you need javascript for anyway).

In issue #443 we discuss allowing validators to reference an external js file. Would that solve your use case?

**Comment by marshall007** [comment]
See also #345 which is similar to #443.

**Comment by deontologician** [comment]
Closing since this was discussed elsewhere, but let us know if you think there's more to consider here
