### ISSUE TITLE
Interacting with Horizon's observables is an enormous pain.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#634]
The single biggest usability problem I've had getting up and running is working with Horizon's observables.  I had three major problems:
1. It isn't obvious what's defined and what isn't.
   - This was extremely frustrating.  We just link to outside documentation on observables, which is reasonable, but has the unfortunate side-effect that I couldn't actually run most examples because we happened not to include some of the operations.
2. It isn't obvious how to add new operations.
   - We have no documentation on our site about how to do this.
   - I _still_ don't know how to do it in the case where you're just writing a script instead of using a build system.
   - It ended up being easier to just download and rebuild Horizon so I could get a client with the commands I needed pre-included.
3. It isn't obvious how to access Horizon's `Observer` class.
   - You need this because some observer commands check that their arguments are from the same class, so you can't e.g. write `hz.currentUser().watch().takeUntil(Rx.Observable.timer(5000))`.
   - I literally ended up writing `Observable = hz.currentUser().watch().constructor` in my code.

I think we can fix the first one by just providing all of `rx-lite` out of the box.  I think the gains in terms of convenience far outweigh the costs in terms of code size.

@Tryneus suggested that we could maybe fix (2) and (3) at the same time by letting users pass us the Observable class they want to use, but I don't know if that's reasonable or not.  (We could also just fix (3) by exporting our `Observable` class somewhere and documenting it.)

**Comment by alf** [comment]
Could you describe how to add operators when using a build system? Would be nice with a workaround until this issue is fixed.

**Comment by deontologician** [comment]
Right now, the easiest way if you have webpack or browserify is to import the `rxjs/add/*` modules, which will monkeypatch Observable. So, for example, to add `reduce`, you'd do:

``` js
import { Observable } from 'rxjs/Observable'
import 'rxjs/add/operator/reduce'
// or in es5:
var Observable = require('rxjs/Observable').Observable
require('rxjs/add/operator/reduce')

// use it like:
myObservable.reduce(...)
```

Alternately, you can grab the bare operators and use them with `.call` or the [function-bind syntax](https://babeljs.io/blog/2015/05/14/function-bind) from babel. The main benefit of this is that it doesn't monkeypatch the global observable class.

``` js
import { Observable } from 'rxjs/Observable'
import { reduce } from 'rxjs/operators/reduce'

// use it like:
reduce.call(myObservable, other, args, go, here)
// or with the :: operator from babel:
myObservable::reduce(other, args, go, here)
```

**Comment by alf** [comment]
I couldn't get monkeypatching to work. It didn't seem to affect the observables created by horizon. I'll give it another go.

**Comment by deontologician** [comment]
It's possible we'll need to export our Observable class. Since we webpack stuff, we're probably using a different Observable than if you also require rxjs. We discuss fixing this by making rxjs a peer dependency in #306 . We also discuss different build options in #611 of which some would have more Observable methods for convenience, and others would be more trimmed down. I think the function-bind syntax is the holy grail solution, but it isn't standards track so it's not worth considering at the moment

**Comment by deontologician** [comment]
I think we should do two things which would be quick and actually can be done for 2.0:
1. Make rxjs a peer dependency per #306 , so users must bring their own. This will fix the instanceof checks and monkeypatch issues we've seen since the user has full access to the Observable, we aren't compiling it into our library.
2. Export the Observable class in `utensils` to solve number 3 above (I'm assuming @mlucy meant `Observable`, not `Observer`. the latter is only an interface, not a class that would be getting instanceof checks)

**Comment by deontologician** [comment]
@alf I think I've discovered the main issue for you with Observable not being the same. We don't define it as a peer dependency, but we also have several builds that don't inline it (leaving it to a global called `Rx` or a commonjs module named `rxjs`). You can try out the version of horizon from `dist/horizon-core.js`, which does not have Observables inlined. You'll need a script tag that sets `window.Rx` to your rxjs 5.0.0 module root

**Comment by marshall007** [comment]
@deontologician this is mostly semantic, but I think for (2) we should just export the entire `Rx` namespace. That way you just have two options:

``` js
import Rx from 'rxjs/Rx';
import Horizon from '@horizon/client';
// or
import { Horizon, Rx } from '@horizon/client';
```

If you only export the `Observable` class I think you're likely to still run into issues with `instanceof` checks since people might still try to grab stuff off the "other" `Rx` instance too.

If you're using a build of Horizon that doesn't include `rxjs` then `horizon.Rx === window.Rx`. Otherwise `horizon.Rx` will be whatever was bundled (which could either be the full `rxjs` or some subset depending on which Horizon build you're using).

**Comment by deontologician** [comment]
I'm poking at this now. I am leaning towards not doing 2 from above. The idea would be to only use the `Rx` global object, which the user would provide, and we'd have no builds which compile in a version of RxJs.

The problem with exposing our `Rx` directly is that even that doesn't allow you to reach everything you can get to through require. For examples, `require('rxjs/observable/dom/webSocket')` isn't reachable from the `Rx` object exported by `@reactivex/rxjs`. So it gets us some things but not all still. Alternately we could explicitly expose everything we use internally, but that sounds kinda gnarly.

**Comment by deontologician** [comment]
Ok, nevermind on that. I had a beta.7 version which didn't export dom, but beta 10 does. I think that is a good idea then, we'll re-export `Horizon.Rx`, and remove deep imports from 'rxjs', just using the kitchen sink version available through global Rx

**Comment by marshall007** [comment]
@deontologician right because when you `import 'rxjs/add/observable/dom/webSocket'` it now defines `Rx.Observable.webSocket`, correct?

**Comment by deontologician** [comment]
`import 'rxjs/add/observable/dom/webSocket'` will add it to `rxjs/Observable`, whether or not there is a global Rx. The entrypoint for the umd version of Rx automatically calls all of the `rxjs/add/*` imports, effectively making `Rx.Observable` a kitchen sink kind of thing (see https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts)

**Comment by deontologician** [comment]
To clarify my current proposal:
- Make rxjs a peerDependency in package.json
- Change all deep imports of rxjs modules to just use the global Rx (equivalently, do `import 'rxjs/Rx'` and tell webpack to fetch that module from the global or from commonjs/amd as appropriate)
- Have the default build of horizon bundle the kitchen sink RxJS
- Have the horizon-core build get rxjs as an external

**Comment by marshall007** [comment]
@deontologician I think the deep imports are still a good idea. Static analysis tools like [`rollup`](https://github.com/rollup/rollup) allow you to only bundle what you use, but it still requires that you use explicit imports. If the user has `rxjs` as a dependency and uses a tool like rollup, they should still be able to import Horizon without suddenly including all of `rxjs` in their bundle.

**Comment by marshall007** [comment]
To clarify, I think our own `client/src/Rx.js` should look a lot like [`rxjs/src/Rx.ts`](https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts), exporting all the things we use. Internally, we would import from `./Rx` instead of `rxjs/Rx`. We would still have the default build of horizon bundle kitchen sink RxJS for convenience, but this way `horizon-core` users still benefit from static analysis because the dependencies are explict.

**Comment by deontologician** [comment]
Ok, so long discussion with @marshall007 on slack, we sorted out the various use cases that are happening here:

| target | how to use | es6 polyfills | node polyfills | includes rxjs |
| --- | --- | --- | --- | --- |
| dist/horizon-core.js | script tag | no | no | no |
| dist/horizon.js | script tag | yes | no | yes |
| lib/* | webpack 1.0 | no | no | no |
| src/* | rollup/webpack 2.0 | no | no | no |

This table doesn't include node.js for the moment. How it'll probably work is that the user will need to provide their own browser api polyfills (like WebSocket) when they are running on node.js

Tasks:
- [ ] add `jsnext:main` for rollup
- [ ] ensure `rxjs/add/*` are no-ops in the horizon-core.js build
- [ ] ensure `rxjs/Observable` returns `Rx` for horizon.js
- [ ] ensure the kitchen sink is bundled with horizon.js
- [ ] ~~make rxjs a peerDependency (#306)~~
- [ ] Move node polyfills from index-polyfill.js to test.js since that's where we use them
- [ ] Make node polyfills devDependencies

**Comment by alf** [comment]
@deontologician I guess relevant information is that I'm using horizon as a linked npm module (I need to build it from source until #507 has landed).

I'm importing Horizon like the following and run everything through webpack.

```
import Horizon from '@horizon/client';
```

**Comment by marshall007** [comment]
@deontologician the more I think about this, the less having a kitchen-sink bundle of `rxjs` makes sense. I think you can really boil it down to two use-cases:
1. Application code only references Horizon public API, no Rx references.
2. Application code also references all or some subset of the Rx API directly.

To meet these use-cases I think we just need:
1. `dist/horizon.js` - I want core and a minimal subset of Rx bundled for it to "just work" (browser).
2. `dist/horizon.core.js` - I just want core - universal/CommonJS module (browser/Node).
3. `src/*` - SystemJS, rollup and/or webpack (ES6)

**Comment by deontologician** [comment]
So far we've seen a fair amount of confusion resulting from operators missing. I'd rather not have to second guess which operators we think will be most useful in order to only get a slight benefit in file size. We can include a subset of operators that cover 95% of use cases, but any individual user is likely to need at least one operator outside that set.

As it is, if you just need one extra operator and you're not using a bundler, it's a pain to extend Observable. The RxJS UMD is not built with operator patching in mind. The nice modular extensibility designed into the library expects you to be using the import system. I'd like to accommodate our `<script>` tag brothers and sisters without causing them a ton of pain. (If you're using a bundler, then you're ignoring `horizon.*.js`, so how many operators we bundle doesn't matter to you.)

If a user is sensitive to size, they can move to Horizon core and hand pick their operators. If you're past the point of prototyping and are looking to streamline your app size, I think that's a reasonable stage to pay the complexity cost of rolling your own Observable.

As an aside, if the function bind `::` operator were standards track, I'd say it would be worth it to have a minimal/rx-lite build in addition to kitchen-sink and bring-your-own-Rx builds, since `::` makes it trivial to extend whatever Observable you happen to be presented with. But, unfortunately, it seems `::` is [not picking up steam](https://github.com/zenparsing/es-function-bind/issues/24).

**Comment by marshall007** [comment]
@deontologician what I'm saying is that `<script>` tag users don't really benefit from having RxJS bundled with Horizon. If their application depends on Rx, they should already have another script tag in place referencing `rx.js`.

In my view, the kitchen sink Rx build doesn't fulfill any use cases. If you don't think the "core and a minimal subset of Rx bundled for it to 'just work'" is a valid use-case then I say we just drop that one too so none of the builds bundle anything from rxjs.

**Comment by mlucy** [comment]
I think we shouldn't continue providing a version which has an essentially random subset of the operators defined.  (Or, at least, I found that decision annoying when using it.)  We should either provide no operators and force people to include Rx before Horizon, or we should provide basically everything.

Assuming there's a way to get at the Observable class inside Horizon, I think bundling it with Horizon makes the first-touch experience much nicer because you don't have to go download anything else to use it.  So, +1 for the original proposal where we provide `horizon.js` with everything and `horizon-core.js` with nothing.

**Comment by intellix** [comment]
just to add a use-case to this:
I've got a navigation of about 20 items, which contain sub-items like:

```
Football
 - NCAAF
 - NFL
Soccer
 - Euro 2016
```

I've got an admin interface to change the order of the sports items, to do this I'm altering the array order, adding an `order` property and then doing `this.service.sports.replace(items)`, which is running on about 20 sports items.

Because we can't do joins, inside the sports-navigation component, I've nested a query inside the subscribe like so:

``` js
// sports-nav.component.ts
this.sportsbookService.sports.order('order').watch().subscribe((sports) => {
  this.sports = sports;
  // TODO: Remove when horizon supports JOINs
  // Fetch leagues and nest them inside of sports
  this.sportsbookService.leagues.fetch().subscribe((leagues) => {
      this.sports.forEach((sport) => {
          sport.leagues = [];
      });
      leagues.forEach((league) => {
        this.sports.forEach((sport) => {
          if (league.sport_id === sport.id) {
            sport.leagues.push(league);
          }
        });
      });
    });
});
```

Because I'm replacing 20 items, the subscribe is triggered 20 times, which is running the inner query 20 times as well.

I'd like to add `.debounceTime(50)` to the `watch()` so lots of updates are batched into one reaction in my component :)
Unless it's possible to do a `replaceAll()` which triggers only one change-feed?

**Comment by marshall007** [comment]
@intellix check out #105 for discussion on aggregating multiple queries like that. In the mean time, something like this should work:

``` js
this.sportsbookService.sports.order('order').watch()
  .combineLatest(this.sportsbookService.leagues.watch())
  .map(pair => {
    let [ sports, leagues ] = pair;
    sports.forEach(s => s.leagues = leagues.filter(l => l.sport_id === s.sport_id))
    return sports
  })
  .subscribe(sports => this.sports = sports)
```

**Comment by deontologician** [comment]
Fixed in ~~#640~~ #638

**Comment by alf** [comment]
Fixed in #638 I suspect.

**Comment by deontologician** [comment]
You're right, I'm a chronic issue mis-numberer

**Comment by ivan-kleshnin** [comment]
FYI RxJS has `let` operator which basically serves as a way to add new functionality
without monkeypatching.

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/let.md

I'd prefer `::` but the current proposal is dead AFAK.
