### ISSUE TITLE
2.0.0-beta-4 currentUser only works with .connect()

### ISSUE THREAD

**Issue by daniel1943** [rethinkdb/horizon#749]
```
  if (typeof window === 'object') {
    const hz = new Horizon();
    if (hz.hasAuthToken()) {
      hz.connect();
      hz.currentUser().fetch().subscribe((user) => console.log(JSON.stringify(user)));
    }
  }
```

Above works, **without hz.connect()** it does't, but it should right? From docs:

> The query result is a user object as described in Users and groups, or an empty object if the user is unauthenticated.

```
const hz = new Horizon();
hz.currentUser().fetch().subscribe( (user) => console.log(JSON.stringify(user)) );``

```

**Comment by danielmewes** [comment]
Thanks for reporting this. It should indeed work without `hz.connect()`, and I thought we had fixed it in https://github.com/rethinkdb/horizon/issues/567 . But apparently the issue came back.

Pinging @deontologician

**Comment by deontologician** [comment]
Ok! I figured this out. Turns out we got burned by rxjs changing its behavior for `.take(0)`. Before it would subscribe and complete immediately, now it's special cased so that it never subscribes to the underlying observable. Arguably better for performance, but we were relying on the side-effect in our code.

I'll have a PR up shortly, I also found another undiagnosed issue that I fixed at the same time.
