### ISSUE TITLE
Ionic DB - Commercial fork of Horizon/RethinkDB

### ISSUE THREAD

**Issue by lgleim** [rethinkdb/horizon#869]
Hi, this is especially targeted at @adamdbradley, @brandyscarney, @danbucholtz, @mlynch, @dwieeb, @mlynch, @mhartington, @nphyatt and anyone else working on the commercial [fork](https://www.npmjs.com/package/@ionic/db) of Horizon called [Ionic DB](https://ionic.io/db).

Since RethinkDB [just became part of the Linux Foundation](https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/) and is [no longer backed by a commercial developer](https://rethinkdb.com/blog/rethinkdb-shutdown/), both RethinkDB and Horizon would greatly benefit from another entity stepping up.

What are the chances that Drifty Co. (the company behind Ionic) is going to do just that and contribute back its improvements to the Horizon and RethinkDB back to the OSS projects? Maybe Drifty could even take a leadership role in an effort to secure its continued development? 

Looking forward to your response!

**Comment by Khalid-Nowaf** [comment]
this is interesting ! 
I think now many company are interested in RethinkDB, since the Apache License is suitable for them now! 

this will make RethinkDB great again <3 !

**Comment by nphyatt** [comment]
@Igliem Thanks for the message! As far as contributing back what we've done to Horizon/RethinkDB I'd love to contribute back what I can. For RethinkDB itself we are just using it as is with no modification but I have done some work on Horizon. We tried to contribute back what we could easily with a few PR's but we've since diverged somewhat (changing the API a little, auth changes specific to Ionic, etc.) which made it harder to contribute back some of the changes that might be of interest to the project. Really at this point the only thing that isn't specific to the Ionic Cloud platform that might be of interest to the OSS project would be some reconnection logic I added which allows for `watch()` queries to persist through a disconnect/auto-reconnect  scenario. I'd be happy to try to port it back to the Horizon OSS project if there is interest in my free-time. 

As far as committing Ionic resources and having Ionic take a leadership role in Horizon I can't officially speak to that. I know we love RethinkDB and Horizon but I'm doubtful that we'll be able to devote much if any resources to assuring it's continuation. IonicDB is currently in beta and part of that beta is that we're trying to evaluate whether it's a valuable product for our users and whether it fits with our offering now and in the future. Hopefully that answers your question!

**Comment by riyadhzen** [comment]
@nphyatt Thanks for taking the time to answer this question and I wish you the best with your project.
One thing that caught my attention in your answer is the reconnection logic that you are implementing in your horizon fork. Currently I am doing application level auto reconnects on the client side without modifying the code base. My Implementation has nothing special in it (just watching for status events). I hope that you take the time to explain your approach, I am sure that this is going to be beneficial to the community and to horizon.

**Comment by lgleim** [comment]
@nphyatt Thank you very much for your response. It is great to hear that you are open towards recontributing your improvements to the project and there has actually been lots of interest in just the feature you implemented. It is actually one of the longest standing open issues: https://github.com/rethinkdb/horizon/issues/9

I hope you succeed with IonicDB and can find some time to port your improvements back to the project. Looking forward to future PRs ;)

**Comment by lgleim** [comment]
@nphyatt I am going to close this issue. Hope to see your solution to https://github.com/rethinkdb/horizon/issues/9 ;)
